### ISSUE TITLE
$HOME/.3ds/logo_hmackey_text?

### ISSUE THREAD

**Issue by ghost** [yellows8/ctr-logobuilder#1]
I've decrypted and decompressed a Home Menu code.bin, exefs dir, and romfs dir but can't find this file anywhere (9.2 old3ds). Anything I'm missing concerning my search methods?

**Comment by yellows8** [comment]
It's binary contained in the exefs codebin......

**Comment by ghost** [comment]
Gbafail to the rescue
http://gbatemp.net/threads/tutorial-edit-the-homemenu.424449/page-35#post-6331757
:-P

**Comment by regimensocial** [comment]
Really sorry for massively necroposting here, but I just can't find logo_hmackey_text anywhere. 
I don't even really know how to look if I'm honest, but I've opened code.bin in HxD and can't find it at all. I'm not sure what the previous person got from the page they linked, but that comment unfortunately has a deadlink to some tool that might've helped. If you could help, I would really appreciate it. Thank you

**Comment by yellows8** [comment]
USA v28673 code.bin offset 0x205465 size 0x20-bytes. (Never really doc'd it before it seems :/)

**Comment by regimensocial** [comment]
Really huge thank you for responding so quickly, and also to something from 7 years ago. Is the filesize of logo_hmackey_text meant to be 20 bytes?

**Comment by yellows8** [comment]
0x20-bytes binary -> `hex 64-character text file, originally extracted from binary`

`xxd -s 2118757 -l 32 -p {path}/code.bin` would also work, with newline removed.

**Comment by regimensocial** [comment]
Thank you, I've finally sorted it out now.
Also I know it's been many years so you're probably not so committed to this repo, but in buildlogo.sh, `sha` should be changed to `sha1`. Thank you again.

**Comment by yellows8** [comment]
Should be `sha256`.

**Comment by regimensocial** [comment]
`-sha256` should still be there, but `openssl sha -sha256 ...` won't work because `sha` needs to be changed to `sha1`.

Otherwise you get `Invalid command 'sha'; type "help" for a list.`.
I think `openssl` might've changed a few things since you made the repo.

**Comment by yellows8** [comment]
Meant `openssl sha256 ...`
